# -*- coding: utf-8 -*-
"""Lab1(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZhR8pnarYEDQDeP_DNQWnN7tGQ88skJB
"""

file_in = open("/content/lab1(b).txt", 'r')
test_case = int(file_in.readline())

arr = []

for _ in range(test_case):
    line = file_in.readline()
    line = list(map(str, line.split()))
    arr.append(line)

print(arr)
output = open("/content/output1(b).txt", 'w')

for i in range(len(arr)):
    operation = arr[i]
    if operation[2] == '+':
        output.write("The result of " + operation[1] + ' ' + operation[2] + ' ' + operation[3] + ' is ' + str(int(operation[1]) + int(operation[3])) + '\n')
    elif operation[2] == '-':
        output.write("The result of " + operation[1] + ' ' + operation[2] + ' ' + operation[3] + ' is ' + str(int(operation[1]) - int(operation[3])) + '\n')
    elif operation[2] == '*':
        output.write("The result of " + operation[1] + ' ' + operation[2] + ' ' + operation[3] + ' is ' + str(int(operation[1]) * int(operation[3])) + '\n')
    elif operation[2] == '/':
        output.write("The result of " + operation[1] + ' ' + operation[2] + ' ' + operation[3] + ' is ' + str(int(operation[1]) / int(operation[3])) + '\n')

file_in.close()
output.close()



