# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jnGbJ-_fiw6O7rYP6gNvOYuRBb3DEwBo
"""

''' Task 2 (1) '''
input_file = open("/content/input2.txt", mode= "r")
output_file = open ("/content/output2(1).txt", mode = "w")

input =input_file.read().split()
Alice_l = int(input[0])
Bob_l = int(input[Alice_l+1])
Alice = [int(i) for i in input[1:Alice_l+1]]
Bob = [int(i) for i in input[Alice_l+2:]]

Merged = Alice + Bob
Merged.sort()
print(Merged)
output_file.write(' '.join(map(str, Merged)))



''' Task 2 (2) '''
def merge(arr1, arr2, array1_size, array2_size):
    len1 = array1_size
    len2 = array2_size
    result = [0] * (len1 + len2)
    i = 0
    j = 0

    for x in range(len(result)):
        if i < len1 and j < len2:
            if arr1[i] <= arr2[j]:
                result[x] = arr1[i]
                i += 1
            else:
                result[x] = arr2[j]
                j += 1
        elif i < len1:
            result[x] = arr1[i]
            i += 1
        elif j < len2:
            result[x] = arr2[j]
            j += 1

    return result


input_file = open("/content/input2.txt", mode= "r")
output_file = open ("/content/output2(2).txt", mode = "w")

input_lines = input_file.readlines()
N = int(input_lines[0].strip())
S = int(input_lines[2].strip())
print("Size of the first array: ",N)
print("Size of the first array: ",S)
array1 = [int(num) for num in input_lines[1].split()]
array2 = [int(num) for num in input_lines[3].split()]
print("First Array: ",array1)
print("Second Array: ",array2)
print("...")
print("Merged: ",merge(array1, array2, N, S))

merged_array = merge(array1, array2, N, S)

output_file.write(' '.join(map(str, merged_array)))

output_file.close()