# -*- coding: utf-8 -*-
"""Lab 01(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EJeXAZ1tUR3UdaRXLnM_8VGtI72vBD6M
"""

file_in = open("/content/input1(a).txt",'r')
# test1 = file_in.readline()
# print(test1)

arr = list(map(int, file_in.read().split("\n")))
print(arr)

file_out = open("/content/output1a.txt",'w')

for i in range(len(arr)):
  if arr[i]%2==0:
    file_out.write(str(arr[i])+' in an Even number.\n')
  else:
    file_out.write(str(arr[i])+' in an Odd number.\n')

file_in.close()
file_out.close()