# -*- coding: utf-8 -*-
"""Task_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zJbhYG7a8P0k4i4fDxc4fBmS5fBRJCE_
"""

input_file = open("/content/input3.txt", mode="r")
output_file = open("/content/output3.txt", mode="w")
input_data = input_file.readlines()
# print(input_data)
Students = int(input_data[0])
print("Number of Student: ",Students)
Student_id = [int(i) for i in input_data[1].split(" ")]
Student_mark = [int(i) for i in input_data[2].split(" ")]
print("Student IDs: ",Student_id)
print("Student's Marks: ",Student_mark)
for i in range(Students-1):
    temp = Student_mark[i]
    temp1 = Student_id[i]
    if Student_mark[i] < Student_mark[i+1]:
        Student_mark[i] = Student_mark[i+1]
        Student_mark[i+1] = temp
        Student_id[i] = Student_id[i+1]
        Student_id[i+1] = temp1

for i in range(Students):
    output_file.write(f"Student_id: {Student_id[i]} Mark: {Student_mark[i]}\n")

output_file.close()
input_file.close()