# -*- coding: utf-8 -*-
"""task1B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pOP7tBQ5DxT055iUNYOQTrsEbbf0nvK9
"""

def bfs_topological(graph):
    indegree = {}
    parent_count = {}
    for node in graph:
        indegree[node] = 0
        parent_count[node] = 0

    for node in graph:
        for neighbor in graph[node]:
            indegree[neighbor] += 1
            parent_count[node] += 1

    queue = []
    for node in graph:
        if indegree[node] == 0:
            queue.append(node)

    topological_order = []
    while queue:
        node = queue.pop(0)
        topological_order.append(node)
        for neighbor in graph[node]:
            indegree[neighbor] -= 1
            parent_count[neighbor] -= 1
            if indegree[neighbor] == 0:
                queue.append(neighbor)

    return topological_order

def read_input(filename):
    with open(filename, 'r') as file:
        n, m = map(int, file.readline().split())
        graph = {i: [] for i in range(1, n + 1)}
        for _ in range(m):
            a, b = map(int, file.readline().split())
            graph[a].append(b)
        return n, graph

def write_output(filename, result):
    with open(filename, 'w') as file:
        if result:
            file.write(" ".join(map(str, result)))
        else:
            file.write("IMPOSSIBLE\n")
def is_dag(graph):
    visited = set()
    stack = set()

    def dfs(node):
        visited.add(node)
        stack.add(node)
        for neighbor in graph[node]:
            if neighbor not in visited:
                if dfs(neighbor):
                    return True
            elif neighbor in stack:
                return True
        stack.remove(node)
        return False

    for node in graph:
        if node not in visited:
            if dfs(node):
                return False
    return True

# Driver code
if __name__ == "__main__":
    input_filename = "/content/input1B_3.txt"
    output_filename = "/content/output1B_3.txt"

    n, graph = read_input(input_filename)

    if is_dag(graph):
        result = bfs_topological(graph)
        write_output(output_filename, result)

        print("Topological order:")
        print(result)
    else:
        write_output(output_filename, [])
        print("IMPOSSIBLE")